version: "2"
services:
  gvmd:
    container_name: gvmd
    image: dvin/gvmd:1.0.1
    volumes:
          - /var/run/postgresql:/var/run/postgresql
    entrypoint:
          - sh
          - -c
          - "while [ 1 ]; do echo . ; sleep 5; done"
