version: "2"
services:
  gsa:
    container_name: gsa
    image: dvin/gsa:1.0.1
    ports:
      - "8160:80"
    entrypoint:
          - gsad
          - -f 
          - --http-only
          - --listen=0.0.0.0
          - -v
#          - sh
#          - -c
#          - "while [ 1 ]; do echo . ; sleep 5; done"
