version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
          - /var/run/postgresql:/var/run/postgresql
